### ISSUE TITLE
Optional log files for simulation data

### ISSUE THREAD

**Issue by LeoBaro** [ambra-dipiano/cta-sag-sci#11]
The simulation code produces fits and log files, such as bkg000001.fits and bkg000001.log. 
I think could be useful, for large sized simulations (e.g. in the order of 10^5 -> 10^7), to not produce the log files or delete them as soon they are created. 

Advantages:
- faster file system operations
- reduced disk occupation (7643 Bytes for each log ==> 7643 * 10^6 ==> 7643 MB )

Is there a particular reason to keep those log files?

**Comment by ambra-dipiano** [comment]
I forgot to close the issue, now it should be default to remove all logs.

#7c928cd
