### ISSUE TITLE
None-check missing

### ISSUE THREAD

**Issue by LeoBaro** [ambra-dipiano/cta-sag-sci#9]
"png" variabile is not checked against the None values, here: https://github.com/ambra-dipiano/cta-sag-sci/blob/devel/RTAscience/lib/RTAVisualise.py#L77

**Comment by ambra-dipiano** [comment]
It was fixed but I forgot to close the issue: [ 8f3cbd2 ](https://github.com/ambra-dipiano/cta-sag-sci/commit/18f7baefee41fd38b3ae8fd1d5f05822042c0a25#diff-d9332df2ed32d856e4709842ab898e398578296f9e35650ec53c235584ecf5b8)
